name: mind_planner
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  dio: ^5.7.0
  get_it: ^8.0.3
  retrofit: ^4.4.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  freezed: ^2.5.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0

global_options:
  freezed:
    runs_before:
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator:retrofit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.9.0
  retrofit_generator: ^9.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/json/